= FSL Community Yocto 2.4 Rocko BSP

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir fsl-community-bsp
$: cd fsl-community-bsp
$: repo init -u https://github.com/TechNexion-customization/fsl-community-bsp-platform.git -b rocko-tn
$: repo sync -j8

== Prepare WIFI/BT firmware
Under `sources/meta-edm-bsp-release/recipes-bsp`, there are two directories: `"firmware-legacy"` and `"firmware-bcmdhd"` which contain wifi/BT firmware files.

. firmware-legacy:
This directory contains wifi/BT firmwares for `BCM4330`, the firmware files are from Linux-Wireless and added by default.

. firmware-bcmdhd:
This directory is supposed to contain the WIFI/BT firmwares of `Ampak AP6335(BCM4339) and AP6212(BCM43438)`.
Because of the license restriction, please contact TechNexion FAE or Sales to get licensed firmware files.
After getting the firmware binary:
.. Put all the firmware files into `sources/meta-edm-bsp-release/recipes-bsp/firmware-bcmdhd/files`.
.. Activate the deployment of `Ampak AP6335(BCM4339) and AP6212(BCM43438) firmware files`:
[source,console]
$: cp sources/meta-edm-bsp-release/recipes-bsp/firmware-bcmdhd/files/firmware-bcmdhd_1.0.1.bak sources/meta-edm-bsp-release/recipes-bsp/firmware-bcmdhd/firmware-bcmdhd_1.0.1.bb


== Configurations for setup script

`“MACHINE”` is the target of build. It usually corresponds to the name of SOM or SBC.

For more information, please check the file under `“sources/meta-edm-bsp-release/conf/machine”`.

`“DISPLAY”` is the disply type. This option only works on i.mx6 (i.mx6 Solo/Dual Lite/Dual/Quad) SOMs and doesn’t work for i.mx6ul, i.mx6sx and i.mx7.

`“BASEBOARD”` is the baseboard type. This option only works on i.mx6 (i.mx6 Solo/Dual Lite/Dual/Quad) SOMs and doesn’t work on i.mx6ul and i.mx6sx.

`“-b”` specify the build directory.

`“-e”` sets the graphical back end for frame buffer and direct fb images. X11 is default if no backend is set.

== Build Yocto for TechNexion target platform
=== For PICO-IMX7

*PICO-IMX7 with PI baseboard:*
[source,console]
$: MACHINE=pico-imx7 source tn-setup-release.sh -b build-fb-imx7 -e fb
$: bitbake fsl-image-machine-test
